### ISSUE TITLE
How to store a set of waypoints for AUTO mode

### ISSUE THREAD

**Issue by stephen-t-dodds** [diydrones/dronekit-python#11]
Hi,

Mavlink allows you to set a group of waypoints to be executed by AUTO mode by using the "set waypointfile.txt" command.

Have you created a function that emulates the "set" command so that waypoints can be saved to the drone? I looked extensively in your documentation and I have not found anything that resembles this command. 

I did notice that in small_demo.py you have access to the waypoints that are already set using cmds[x] structure:

cmds = v.commands
cmds.download()
cmds.wait_valid()
print "Home WP: %s" % cmds[0]
print "Current dest: %s" % cmds.next

However, you cannot save to the cmds[x] structure, you have only given access to printing the contents (at least as far as my experimentation has shown me).

If there is not such a function in droneapi yet, would you please make one? I do not mind making the text file if you could make some sort of function that "sets" the text file as the waypoints. However, It would be even more nice if you had a way to just "set" waypoints into the AUTO mode list using some sort of structure.

Thanks,

Stephen

**Comment by hamishwillee** [comment]
This question is quite old, so I assume either you worked this out or the functionality was fixed. The latest API reference (not "quite" being displayed) shows how to upload commands (well, a single command, but it is the same thing):
```
cmds = vehicle.commands
cmds.clear()
lat = -34.364114, 
lon = 149.166022
altitude = 30.0
cmd = Command(0,0,0, mavutil.mavlink.MAV_FRAME_GLOBAL_RELATIVE_ALT, mavutil.mavlink.MAV_CMD_NAV_WAYPOINT,
    0, 0, 0, 0, 0, 0,
    lat, lon, altitude)
cmds.add(cmd)
vehicle.flush() 
```

The documentation also updates the instructions on the channel_override (renamed from rc_override). Generally speaking the recommendation is that these are not really intended to be used except for simulating user input or some system for providing user input (like a joystick). Instead movement can be controlled in missions using the commands, or in guided mode using Vehicle.goto, custom commands or parameters.

I'm setting this closed on the assumption the issue is resolved. We will be writing more "guide" documentation on these topics.
